[phases.install]
cmds = ["npm config set cache /tmp/.npm", "npm install --prefer-offline --no-audit"]

[phases.build]
cmds = ["npm run build", "npx prisma generate"]

[start]
cmd = "npm run start:prod"

