[phases.setup]
nixPkgs = ["nodejs-20_x", "npm"]

[phases.install]
cmds = ["npm ci --cache /tmp/.npm"]

[phases.build]
cmds = ["npm run build", "npx prisma generate"]

[start]
cmd = "npm run start:prod"

